# Generated by Django 4.2.30 on 2026-05-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianprofile',
            name='skills',
            field=models.TextField(help_text='Example: WiFi, Router Setup, CCTV, LAN Cabling'),
        ),
    ]
