# Generated by Django 4.2.30 on 2026-05-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0002_alter_technicianprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='technician_profiles/'),
        ),
    ]
