# Generated by Django 4.2.30 on 2026-05-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0003_technicianprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianprofile',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], default='available', max_length=20),
        ),
    ]
