# Generated by Django 4.2.30 on 2026-05-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0002_servicerequest_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes visible only to FixNet admin.'),
        ),
    ]
