# Generated by Django 4.2.30 on 2026-05-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0003_servicerequest_admin_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='price_note',
            field=models.TextField(blank=True, help_text='Reason for final price change or pricing explanation.'),
        ),
    ]
