# Generated by Django 4.2.30 on 2026-05-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0004_servicerequest_price_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank', 'Bank Transfer'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='payment_note',
            field=models.TextField(blank=True, help_text='Internal payment note or transaction reference.'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
    ]
