# Generated by Django 4.2.30 on 2026-05-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0005_servicerequest_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='payment_proof',
            field=models.ImageField(blank=True, help_text='Screenshot or receipt proof of payment.', null=True, upload_to='payment_proofs/'),
        ),
    ]
