# Generated by Django 4.2.30 on 2026-05-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0006_servicerequest_payment_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='payment_proof_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_submitted', max_length=30),
        ),
    ]
