# Generated by Django 4.2.30 on 2026-05-21 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests_app', '0007_servicerequest_payment_proof_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('started', 'Started'), ('completed', 'Completed'), ('status_updated', 'Status Updated'), ('payment_updated', 'Payment Updated'), ('proof_uploaded', 'Proof Uploaded'), ('notes_updated', 'Notes Updated'), ('price_updated', 'Price Updated')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='requests_app.servicerequest')),
            ],
            options={
                'verbose_name_plural': 'Request activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
