# Generated by Django 4.2.30 on 2026-05-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0008_requestactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason why this request was cancelled.'),
        ),
    ]
