# Generated by Django 4.2.30 on 2026-05-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0009_servicerequest_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='platform_commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='platform_commission_percent',
            field=models.DecimalField(decimal_places=2, default=20, help_text='Platform commission percentage.', max_digits=5),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='technician_earning',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
