# Generated by Django 4.2.30 on 2026-05-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0010_servicerequest_platform_commission_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='technician_payout_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='technician_payout_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank', 'Bank Transfer'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='technician_payout_note',
            field=models.TextField(blank=True, help_text='Internal payout note or transaction reference.'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='technician_payout_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
    ]
