# Generated by Django 4.2.30 on 2026-05-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['display_order', 'name'], 'verbose_name_plural': 'Service categories'},
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='estimated_response_time',
            field=models.CharField(blank=True, help_text='Example: Within 30 minutes, Same day, 24 hours', max_length=100),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Estimated starting price in UGX', max_digits=12),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Example: wifi, router, camera, cable', max_length=50),
        ),
    ]
